### ISSUE TITLE
vite-package when registered locally instead of globally fails with "Component is missing template or render function at Anonymous"

### ISSUE THREAD

**Issue by garylake** [matthewmaribojoc/learnvue-learning-paths#1]
Hi Matt

I've been following your youtube video to publish a Vue component to NPM. Firstly, thank you and it's brilliant. 

In short, I have a component that others might find useful and wanted to have a go at publishing it, so your video has been hugely helpful. I've just become stuck and hit an issue when testing my own component. 

I migrated my component to a new vite project and followed all your steps. I then went back to my project where the component originally came from and tried to swap it out for my npm linked one. 

If I do this by registering it globally in my main.js it works. However, with the original component I was actually loading it locally for tree shaking purposes etc. Now when I try and register it locally I get "Component is missing template or render function at Anonymous" and it fails silently. 

I wanted to rule out my own mistakes so I've cloned your repo/tutorial and tried to recreate the issue and I do in fact get "Component is missing template or render function at Anonymous" – I have a branch with this on but I can't push due to permissions.

To recreate what I did was:
* remove lv-button from package.json
* npm install and vite build in both vite-package and pkg-test
* npm link in vite-package
* npm link lv-button in pkg-test

In pkg-test/src/main.js, If I leave lv-button registered globally, everything works as expected. 

But If I comment it out – e.g. 

```
import { createApp } from "vue";
import App from "./App.vue";
// import LearnVueButton from "lv-button";
// import "lv-button/dist/style.css";

const app = createApp(App);

// app.use(LearnVueButton);

app.mount("#app");
```

And migrate it to App.vue to register it locally (I'm just simulating what I'm trying to do in a more complex app):

```
<script setup>
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
import HelloWorld from "./components/HelloWorld.vue";
import LearnVueButton from 'lv-button';
import "lv-button/dist/style.css"; 
</script>

<template>
  <HelloWorld />
  <LearnVueButton> Hello world! </LearnVueButton>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

Then I get "Component is missing template or render function at Anonymous". Now if this component was not in node-modules but just pulled in via ./src/components like HelloWorld.vue is, I'd expect it to work. 

I'm new to node_modules so should this work or is the issue I'm having expected and you have to register globally?

Thanks in advance!

**Comment by garylake** [comment]
@matthewmaribojoc appreciate you're probably super stacked etc – at this stage if I could get a: 
"Yeah, weird, that should work", OR
"You're doing something wrong but I don't have time to figure it out", OR
"You just can't do that"

That would be sweet and I will just go away and figure it out... 

Cheers and keep up the good work!

**Comment by matthewmaribojoc** [comment]
Hey @garylake - sorry about taking so long.

Full transparency, not 100% sure of the solution. But from my few minutes of poking around other projects, I think you would have to switch the approach from the package exporting a plugin, to just exporting the component itself. 

`LearnVueButton` in the repo is not a component, but rather a plugin that globally adds the component. 

So I think you would have to switch `index.js` to export the component itself, then it should be able to be imported. [Here's](https://github.com/formkit/formkit/blob/master/packages/inputs/src/index.ts) a good example from FormKit on how they do it. 

Let me know if this helps

**Comment by garylake** [comment]
@matthewmaribojoc just a quick one, that totally worked!

Replaced: 
```
import LearnVueButton from "./components/LearnVueButton.vue";

export default {
  install: (app, options) => {
    app.component("LearnVueButton", LearnVueButton);
  },
};
```

with 
```
import LearnVueButton from './components/LearnVueButton.vue';

export { LearnVueButton };
```

And local registration worked!  🙏🏻

**Comment by matthewmaribojoc** [comment]
@garylake great find! i'll add that to the README

**Comment by garylake** [comment]
The reason for this is I'm working up to publishing my first bit of open source, a Vue Dynamic Heroicons component. I've probably done it wrong but I built it for myself (I'm using a lot of Heroicons and I wanted the ability to just import them by name adhoc) and I thought it might be useful and tbh, I just wanted to actually get some feedback on something and learn from it. Anyway, I'll ping you when it's published because this tutorial was a massive help. 

I'm likely going to be moving my whole components directory to a library now as I may be building two apps for the same project/company, so again, huge thanks!

**Comment by mbesagil** [comment]
Great but only uses a single component. If you want to use multiple nested components, you will encounter a warning. Is there a solution to this Please Help Me :) 

ex. - > 

<script setup>
import TestButton2 from "./TestButton2.vue";

const testbutton = () => {
  console.log("clicked");
};
</script>

<template>
  <div>
    <span>Test Button 1</span>
    <button class="btn btn-primary" @click="testbutton">Click Me</button>
    <div>
      <span>Test Button 2</span>
      <TestButton2></TestButton2>

      
      
      
      
    </div>
  </div>
</template>


error. ->

PS C:\Users\musab\OneDrive\Belgeler\mesut\npm test\canli test\npm-live-test> npm run dev

> npm-live-test@0.0.0 dev
> vite


  VITE v4.4.9  ready in 400 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/@mbesagilpublics/master-lib/dist/my-lib.js:4:7:
      4 │ import require$$0, { getCurrentScope, onScopeDispose, unref, getCurrentInstance, onMounted, nextTick, watch, ref, openBlock, createElementBlock, createElementVNode, warn, computed, inject, isRef, shallowRef, ...
        ╵        ~~~~~~~~~~

C:\Users\musab\OneDrive\Belgeler\mesut\npm test\canli test\npm-live-test\node_modules\esbuild\lib\main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@mbesagilpublics/master-lib/dist/my-lib.js:4:7: ERROR: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    at failureErrorWithLog (C:\Users\musab\OneDrive\Belgeler\mesut\npm test\canli test\npm-live-test\node_modules\esbuild\lib\main.js:1649:15)
    at C:\Users\musab\OneDrive\Belgeler\mesut\npm test\canli test\npm-live-test\node_modules\esbuild\lib\main.js:1058:25
    at C:\Users\musab\OneDrive\Belgeler\mesut\npm test\canli test\npm-live-test\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: 'node_modules/@mbesagilpublics/master-lib/dist/my-lib.js',
        length: 10,
        line: 4,
        lineText: 'import require$$0, { getCurrentScope, onScopeDispose, unref, getCurrentInstance, onMounted, nextTick, watch, ref, openBlock, createElementBlock, createElementVNode, warn, computed, inject, isRef, shallowRef, onBeforeUnmount, onBeforeMount, provide, defineComponent, mergeProps, renderSlot, toRef, onUnmounted, useAttrs as useAttrs$1, useSlots, withDirectives, createCommentVNode, Fragment, normalizeClass, createBlock, withCtx, resolveDynamicComponent, withModifiers, createVNode, toDisplayString, normalizeStyle, vShow, Transition, reactive, onUpdated, cloneVNode, Text, Comment, Teleport, readonly, onDeactivated, renderList, createTextVNode, toRaw, vModelCheckbox, toRefs, vModelRadio, withKeys, triggerRef, resolveComponent, resolveDirective, vModelText, createSlots, h as h$1, watchEffect, hasInjectionContext, effectScope, isReactive, markRaw, createStaticVNode, pushScopeId, popScopeId, KeepAlive } from "vue";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"'
    }
  ],
  warnings: []
}

Node.js v18.15.0
